ConfigVersion: 1

Update:
  # Notify console of updates?
  Notify: true
  # Automatically download and install updates
  Download: false

# Double spaces will be removed, so if a player doesn't have a prefix there wont be a big gap
# You can use PlaceholderAPI tags here if it is installed
# You can add the {FACTION} tag if you have the faction add-on installed
DefaultFormat: "{CHANNEL_PREFIX} {PREFIX} {NAME} {SUFFIX} &7>&f {MESSAGE}"

# How often in milliseconds can a player send a message
RateLimit: 1000

# enable this if your console doesn't support color codes but still shows them
StripColorFromConsole: true

Channels:
  Global:
    Prefix: "[G]"
  Local:
    Prefix: "[L]"
    # Distance in blocks, this is the distance messages will travel in the local channel
    Range: 100